export interface Product {
  id: string; // Auto-generated by backend, e.g. PRODUCT001
  name: string;
  category: string;
  reorderLevel: number;
  unitPrice: number;
  stock?: number; // Usually returned in responses or update
}

export interface Batch {
  id?: string;
  productId: string;
  productName?: string;
  batchNumber: string;
  quantity: number;
  manufactureDate: string;
  expiryDate: string;
  supplierId: number;
  locationId: number;
  purchasePrice: number;
  receivedDate?: string; // Might be mapped from backend or not needed
  status?: 'FRESH' | 'EXPIRING_SOON' | 'EXPIRED'; // Computed frontend side or returned by backend
}

export interface Supplier {
  id?: number;
  name: string;
  contactEmail: string;
  phone: string;
  rating?: number;
}

export interface Location {
  id?: number;
  warehouse: 'FREEZER' | 'DRY' | 'COLD' | string;
  section: string;
  shelf: string;
  capacity: number;
}

export interface Notification {
  id: string;
  message: string;
  read: boolean;
  createdAt: string;
}

export interface Reorder {
  id: string;
  productId: string;
  quantity: number;
  status: string;
  createdAt: string;
}

export interface InventoryAdjustment {
  id: string;
  productId: string;
  batchId?: string;
  type: 'IN' | 'OUT' | 'ADJUSTMENT';
  quantity: number;
  reason: string;
  date: string;
  user: string;
}

export interface DashboardStats {
  totalProducts: number;
  totalBatches: number;
  lowStockItems: number;
  activeAlerts: number;
  recentActivity: {
    id: string;
    description: string;
    timestamp: string;
    type: 'ALERT' | 'INVENTORY' | 'SYSTEM';
  }[];
}

export interface Alert {
  id: string;
  productName: string;
  currentStock: number;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  createdAt: string;
  resolved: boolean;
}
